// <auto-generated />
namespace SuperM.Data.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StockIn_Inventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockIn_Inventory));
        
        string IMigrationMetadata.Id
        {
            get { return "201803031451030_StockIn_Inventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
